[package]
name = "ariel-ml"
version = "0.1.0"
edition = "2024"

[dependencies]
ariel-os = { path = "build/imports/ariel-os/src/ariel-os", features = [] }
ariel-os-boards = { path = "build/imports/ariel-os/src/ariel-os-boards" }
[features]
default = ["resnet50"]
simple_mul = []
resnet50 = []
