include = "../build/imports/ariel-os/ariel-os-cargo.toml"

[unstable]
# This is needed so the "include" statement above works.
config-include = true


[build]
rustflags = ["-C", "link-arg=-Wl,-rpath=/home/zhaolan/miniconda3/envs/ariel_ml/lib/python3.12/site-packages/iree/compiler/_mlir_libs/"]
rustdocflags = ["-C", "link-arg=-Wl,-rpath=/home/zhaolan/miniconda3/envs/ariel_ml/lib/python3.12/site-packages/iree/compiler/_mlir_libs/"]
[env]
LIB_IREE_COMPILER = "/home/zhaolan/miniconda3/envs/ariel_ml/lib/python3.12/site-packages/iree/compiler/_mlir_libs/"